### ISSUE TITLE
Clientside clocks should not depend on handle_notify messages to be stopped on game end

### ISSUE THREAD

**Issue by rogers-j** [Zamiell/keldon-hanabi#18]
Clients in a replay at the end of a timed game do not handle the `game_over` notify from the server immediately.
   
Clients that are _not_ in a replay at the end of a timed game may experience a data race between the final clock message (setting the next timer) and the `game_over` notify (unsets any existing timer). Moving the responsibility entirely to the clock messages should address this.

In both cases, onscreen timers should stop and duration sound effects should not play after the relevant clock message.

**Comment by Zamiell** [comment]
can close this now?

**Comment by Zamiell** [comment]
why did you assign me to this after i already fixed it

**Comment by Zamiell** [comment]
what do i need to do to fix this, i dont understand
