### ISSUE TITLE
Highlight Play Stacks when mousing over a player's card in hand

### ISSUE THREAD

**Issue by MeGotsThis** [Zamiell/keldon-hanabi#26]
This applies best to mixed-color and multi-color games. But it does work on all other modes.
Only with color clues.
Mousing over a card in any hand should highlight all possible play stacks it can match.

Example:
Mousing over Zamiel's slot 1, which only has a Blue clue. Notice the Yellow border in the play area.
![image](https://user-images.githubusercontent.com/9635309/28303152-673fd2b4-6b46-11e7-99e4-098b8987a1a2.png)

Mousing over Zamiel's slot 2, which has positive Red and negative blue. Only 2 play areas are highlighted
![image](https://user-images.githubusercontent.com/9635309/28303250-fd52af1a-6b46-11e7-84fe-73034686588f.png)

Mousing over Zealousy's slot 4
![image](https://user-images.githubusercontent.com/9635309/28303531-8d1f88ec-6b48-11e7-9278-3bd0a4f329fa.png)

Mousing over MeGotsThis's slot 3
![image](https://user-images.githubusercontent.com/9635309/28303717-5431bfd6-6b49-11e7-9ab8-9ba278ac6c26.png)

Mousing over Instantiation slot 4 or 5
![image](https://user-images.githubusercontent.com/9635309/28303316-6ab6f85e-6b47-11e7-8a14-dc61fda98e0c.png)

Mousing over MeGotsThis's slot 5
![image](https://user-images.githubusercontent.com/9635309/28303402-d7d74ee8-6b47-11e7-9cb8-b87465bdd795.png)

Cak's slot 4
![image](https://user-images.githubusercontent.com/9635309/28303822-dd5c6306-6b49-11e7-98c8-7a58397ec3ad.png)

910dan's slot 3 or 5
![image](https://user-images.githubusercontent.com/9635309/28303961-7a38a7ac-6b4a-11e7-9df4-e5f7b559b6b7.png)

**Comment by Zamiell** [comment]
closing in favor of #59
