### ISSUE TITLE
make resize window work without having to refresh

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/keldon-hanabi#36]

**Comment by Zamiell** [comment]
Something like:
```
window.addEventListener('resize', this.build_ui, false);
```
It doesn't fire though if you put it inside the HanabiUI object.
So I'm not sure how to proceed.

**Comment by Zamiell** [comment]
chrono is making progress on this

**Comment by Tempus** [comment]
Two implementations are complete, the first, significantly shittier implementation requires a loading time on each resize. The second implementation is complete, however during testing I found two outstanding bugs: The spectator icon will not appear on resize if no spectators are present, and during a shared replay the shared replay button will disappear on resize.

**Comment by Tempus** [comment]
Will continue until second (the good one) is complete and bug-free, then push.

**Comment by Tempus** [comment]
https://github.com/Zamiell/keldon-hanabi/commit/0fbfbd7943969b462bfe3686bd68a86c77768e71

**Comment by rogers-j** [comment]
There's a follow-up issue here where resizing while rewinding does not properly reset everything.
