### ISSUE TITLE
Allow non-shared navigation during a shared replay

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/keldon-hanabi#58]
The current UI allows clients to navigate individually, but any leader action immediately resets all clients to the turn viewed by the leader.

When the leader is searching for a particular turn, clients move rapidly.

Solution: replace the current button for jumping to the shared turn with a new toggle button for suppressing shared replay messages. A second press returns to the shared position (the current behaviour). For the leader, the button prevents replay messages from being _sent_.

**Comment by rogers-j** [comment]
If a client navigates any other way (buttons, keys), that should effectively also toggle the button.

**Comment by rogers-j** [comment]
2a9cd32d54a816f66ae31ce2a684667f6acc5b39
