### ISSUE TITLE
Improve history view 

### ISSUE THREAD

**Issue by rogers-j** [Zamiell/keldon-hanabi#67]
The most common case is viewing the user's own game.

Current image:
![history_old](https://user-images.githubusercontent.com/5349111/29264684-e0f06aae-8092-11e7-8c46-f267eb6ee8da.png)

Proposed design:
![history_new](https://user-images.githubusercontent.com/5349111/29264693-e50cb160-8092-11e7-8665-a116f1890fad.png)

**Comment by Zamiell** [comment]
excellent work

**Comment by rogers-j** [comment]
![image](https://user-images.githubusercontent.com/5349111/29393968-21960c32-82bc-11e7-8c89-a01dd68ef220.png)
