### ISSUE TITLE
Display game dates in top-level game history

### ISSUE THREAD

**Issue by aliblong** [Zamiell/keldon-hanabi#69]
We have some extra space in the player's top-level game history to display the dates that games were played. It's not information that's always of interest, but it seems better than having nothing there, and I don't think it will clutter the screen even in 1920x1080 resolution.

[This](http://i.imgur.com/1SKCCxD.jpg) is what the top-level history looks like currently in 1680x1050, for reference.

**Comment by Zamiell** [comment]
it should also display the player names in the game

**Comment by Zamiell** [comment]
ADD PLAYERS TO THE RIGHT SIDE

**Comment by Zamiell** [comment]
push this to master?
