### ISSUE TITLE
Server kicks players out of the game

### ISSUE THREAD

**Issue by aliblong** [Zamiell/keldon-hanabi#70]
I got this two games in a row, on different accounts. The first was on an account called simply "🌈". The second was on my main account (Libster). Around halfway through the game, I receive a notification that the table no longer exists. The first time, on 🌈, I was unable to log in again. The second time, on Libster, I was able to log back in immediately, and was able to spectate the game, since my hand and spot at the table had disappeared. No game numbers because both games were manually killed. Also no console logs because they cleared when I refreshed.

**Comment by Zamiell** [comment]
These are the logs from that day: https://pastebin.com/fbH2EALX

Find the spot where you disconnected.

**Comment by Zamiell** [comment]
hasnt happened since, probably something to do with the stupid rainbow account that you were using, dont use stupid accounts
