### ISSUE TITLE
ARROWS

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/keldon-hanabi#74]
GLORIOUS FUCKING ARROWS

**Comment by Zamiell** [comment]
AND THEN AFTER ARROWS SOME FUCKING BORDER YEAAAAAAAHHHH

**Comment by aliblong** [comment]
Thanks to your use of all-caps I am now sufficiently enthusiastic to work on this

**Comment by Zamiell** [comment]
FUCK YES, ENTHUSIASM

**Comment by aliblong** [comment]
Replace clue dots with golden border; replace white border with arrows.
Partially-transparent golden border for replay cards that are clued-in-the-future.

**Comment by Zamiell** [comment]
done

**Comment by rogers-j** [comment]
Followup: #82

**Comment by Zamiell** [comment]
nicely done
