### ISSUE TITLE
Show teammate names in lobby history

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/keldon-hanabi#75]
Player names to the right of the "Other Scores" button

Similar to #69

**Comment by Zamiell** [comment]
server now puts players property in object

**Comment by rogers-j** [comment]
Do you want `exports.getAllDeals` to also send the names?

**Comment by Zamiell** [comment]
https://github.com/Zamiell/keldon-hanabi/commit/f6058fd963e0c2a351107ffad758dbd04096059c

**Comment by rogers-j** [comment]
83b0fe35fb52c805bbb966b89ea5d3425f7130de
